version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  commit-message:
      prefix: "php packages"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor","version-update:semver-major" ]
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "github-actions"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor","version-update:semver-major" ]
  - package-ecosystem: npm
    directory: /
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor","version-update:semver-major" ]
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor","version-update:semver-major" ]
    commit-message:
      prefix: "docker"
        
