import CurrentUrlBlock from "@/CurrentUrlBlock"
import type {Metadata} from 'next'
import {FunctionComponent, ReactNode, Suspense} from "react"


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const RootLayout: FunctionComponent<{
    children: ReactNode
}> = ({children}) => {
    return (
        <html lang="en">
        <body>
        <Suspense>
            <CurrentUrlBlock/>
        </Suspense>
        {children}
        </body>
        </html>
    )
}
export default RootLayout
